// Generated by CoffeeScript 1.9.3
(function() {
  var URI, mod;

  URI = require('URIjs');

  mod = angular.module('ngAidbox', ['ng']);

  mod.service('$aidbox', function($http, $cookies, $window) {
    var access_token, box_url, config, loginUrl, out, query;
    config = {
      client_id: 'site',
      grant_type: 'implicit',
      scope: 'ups',
      redirect_uri: $window.location
    };
    box_url = null;
    query = URI($window.location.search).search(true);
    loginUrl = function() {
      return URI(box_url).directory('/oauth/token').setQuery(config);
    };
    access_token = function() {
      return $cookies.get('ab_' + config.client_id);
    };
    out = function() {
      return $cookies.remove('ab_' + config.client_id);
    };
    this.onAccessToken = (function(_this) {
      return function(query) {
        return _this.user(function(x) {
          if (config.onUser) {
            return config.onUser(x);
          }
        });
      };
    })(this);
    $window.onAccessToken = this.onAccessToken;
    this.init = function(param) {
      var k, v;
      box_url = param.box;
      delete param.box;
      for (k in param) {
        v = param[k];
        config[k] = v;
      }
      if (access_token()) {
        console.log('access_token', access_token());
        this.onAccessToken();
      }
      if (query.access_token) {
        $cookies.put('ab_' + config.client_id, query.access_token);
        $window.opener.onAccessToken(query);
        if ($window.opener) {
          return $window.close();
        }
      }
    };
    this.signin = function(userCb) {
      if (access_token()) {
        return console.log('You are signed in');
      } else {
        $window.open(loginUrl(), "SignIn to you Box", "width=780,height=410,toolbar=0,scrollbars=0,status=0,resizable=0,left=100,top=100");
        return true;
      }
    };
    this.signout = function() {
      if (access_token()) {
        return $http.get(box_url + '/signout', {
          params: {
            access_token: access_token()
          }
        }).success(function(data) {
          out();
          return console.log("You are now logged out");
        }).error(function(err) {
          out();
          return console.log("Wrong access_token", err);
        });
      } else {
        return console.log("You are not logged");
      }
    };
    this.user = function(callback) {
      return $http.get(box_url + '/user', {
        params: {
          access_token: access_token()
        }
      }).success(function(data) {
        if (callback) {
          return callback(data);
        }
      });
    };
    return this;
  });

  module.exports = mod;

}).call(this);
